[New] Show coordinates in multiple formats
Esri/arcgis-maps-sdk-swift-samples pull request #190
Opened 2023-05-31 18:55 UTC by CalebRas

## Description

This PR implements `Show coordinates in multiple formats` in `Geometry` category.
URL to README: https://github.com/Esri/arcgis-maps-sdk-swift-samples/tree/Caleb/New-FormatCoordinates/Shared/Samples/Show%20coordinates%20in%20multiple%20formats

## Linked Issue(s)

- `swift/issues/4129`

## How To Test

* Tap on the map to see the different coordinate formats for the tapped point.

## Screenshots

![show-coordinates-in-multiple-formats](https://github.com/Esri/arcgis-maps-sdk-swift-samples/assets/34120440/192ec5d5-2244-40fe-b4fb-c128e314f02d)

2023-06-06 03:29 UTC, yo1995 commented on Shared/Samples/Show coordinates in multiple formats/ShowCoordinatesInMultipleFormatsView.swift
> +        }()
These can be set in the initializer. Also, in most cases we can use `let`.

2023-06-06 03:29 UTC, yo1995 commented on Shared/Samples/Show coordinates in multiple formats/ShowCoordinatesInMultipleFormatsView.swift
> +        @Published var latLongDDTextField = ""
Instead of "…TextField", change their names to "…String" to make them read better

2023-06-07 16:54 UTC, zkline101 requested changes

2023-06-07 16:54 UTC, zkline101 commented on Shared/Samples/Show coordinates in multiple formats/ShowCoordinatesInMultipleFormatsView.swift
> +            pointGraphic = Graphic(symbol: SimpleMarkerSymbol(style: .cross, color: .yellow, size: 20))
These declarations can both be used where the property is declared they don't need to be in the init.

2023-06-07 16:54 UTC, zkline101 commented on Shared/Samples/Show coordinates in multiple formats/ShowCoordinatesInMultipleFormatsView.swift
> +                addSpaces: true)
```suggestion
            latLongDMSString = CoordinateFormatter.latitudeLongitudeString(
                from: mapPoint,
                format: .degreesMinutesSeconds,
                decimalPlaces: 1
            )
            
            utmString = CoordinateFormatter.utmString(
                from: mapPoint,
                conversionMode: .latitudeBandIndicators,
                addSpaces: true
            )
            
            usngString = CoordinateFormatter.usngString(
                from: mapPoint,
                precision: 4,
                addSpaces: true
            )
```

2023-06-08 18:28 UTC, yo1995 reviewed
Another problem I noticed is when the sample is in iPhone 14 PM landscape orientation, the textfields take up the entire screen. I don't think it is an issue or a need to add a scroll view as no one gonna use the sample that way. 😼

2023-06-08 18:28 UTC, yo1995 commented on Shared/Samples/Show coordinates in multiple formats/ShowCoordinatesInMultipleFormatsView.swift
> +        @Published var mapPoint: Point!
A second thought: I feel it is better to be a state variable in the view than a published property in the model.

1. It doesn't drive UI updates, so it doesn't need to be published
2. I feel in most cases the published properties are private(set), public get. If it is both public set and get, then just staying in the view is fine.
3. If this suggestion is applied, method signature can change to `private func updateCoordinateFields(mapPoint: Point)`.

2023-06-12 17:36 UTC, yo1995 submitted a review, later dismissed

2023-06-12 19:50 UTC, zkline101 commented on Shared/Samples/Show coordinates in multiple formats/ShowCoordinatesInMultipleFormatsView.swift
> +    @State private var mapPoint = Point(latitude: 0, longitude: 0)
I think `tappedPoint` would better describe this property.

2023-06-12 19:52 UTC, zkline101 commented
> Another problem I noticed is when the sample is in iPhone 14 PM landscape orientation, the textfields take up the entire screen. I don't think it is an issue or a need to add a scroll view as no one gonna use the sample that way. 😼

Shouldn't we fix that though? We can't really predict how the user is going to use the app but I think we should make sure the sample looks right in all scenrios.

2023-06-12 20:02 UTC, yo1995 commented
I was afraid that might be too much for Caleb to implement, and add a lot of adaptive UI code that isn't related to the sample. But I'm happy if you want to try that out, either with an adaptive stack view like the old sample, or sth like a LazyVGrid in a scroll view.

2023-06-12 20:31 UTC, zkline101 approved these changes

2023-06-12 20:40 UTC, yo1995 approved these changes
If you want, you can add a note and rework the UI in the second half of the internship.

2023-06-12 20:56 UTC, merged