[Update] `GeometryEditor` sample enhancements
Esri/arcgis-maps-sdk-swift-samples pull request #246
Opened 2023-08-11 22:33 UTC by zkline101

## Description
Changes: 
- Renames the geometry editor sample from `Sketch on map` -> `Create and edit geometries`
- Add shape tool feature to the sample
- Add uniform scale toggle to the sample 

## Linked Issue(s)

- `swift/issues/4382`

## How To Test

The shape tool can be tested by clicking on "Shapes" in the main menu and the uniform scale toggle can be tested in the menu after clicking on a tool.

## Screenshots
![Simulator Screenshot - iPhone 14 Pro Max - 2023-08-11 at 15 29 43](https://github.com/Esri/arcgis-maps-sdk-swift-samples/assets/74069582/941b3b3a-bf0e-47f4-a6d7-b15a48d5593e)
![Simulator Screenshot - iPhone 14 Pro Max - 2023-08-11 at 15 30 05](https://github.com/Esri/arcgis-maps-sdk-swift-samples/assets/74069582/9dc4a052-892f-4583-b1a6-a9cdeaa0c981)

2023-08-11 23:14 UTC, yo1995 reviewed
Mostly looking good!

2023-08-11 23:14 UTC, yo1995 commented on Shared/Samples/Create and edit geometries/sketch-on-map-1.png
Can you recapture the screenshots as the sample title changed?

2023-08-11 23:14 UTC, yo1995 commented on Shared/Samples/Create and edit geometries/CreateAndEditGeometriesView.swift
> +    /// Start editing with the specified tool and geometry type.
```suggestion
    /// Starts editing with the specified tool and geometry type.
```

2023-08-11 23:14 UTC, yo1995 commented on Shared/Samples/Create and edit geometries/README.md
Can you also take a look at "How it works" section in the README and revise the phrasing according to `common-samples/pull/3858`? Or even better, compare the README to the design and fix the discrepancies. Thanks!

2023-08-15 17:53 UTC, yo1995 commented on Shared/Samples/Create and edit geometries/README.md
Can you match the tags to the design, and update the metadata again? Thanks

> draw, edit, freehand, geometry editor, sketch, vertex

2023-08-15 17:53 UTC, yo1995 commented on Shared/Samples/Create and edit geometries/README.metadata.json
> +    "category": "",
```suggestion
    "category": "Maps",
```

2023-08-15 18:05 UTC, yo1995 submitted a review, later dismissed

2023-08-15 18:41 UTC, pgruenler requested changes
Looks good, just one grammar change.

2023-08-15 18:41 UTC, pgruenler commented on Shared/Samples/Create and edit geometries/README.md
> +1. Create an `GeometryEditor` and assign it to a map view with the `geometryEditor` view modifier.
```suggestion
1. Create a `GeometryEditor` and assign it to a map view with the `geometryEditor` view modifier.
```

2023-08-15 18:59 UTC, yo1995 approved these changes

2023-08-15 19:05 UTC, pgruenler approved these changes

2023-08-15 20:09 UTC, merged