[New] Find closest facility from point
Esri/arcgis-maps-sdk-swift-samples pull request #297
Opened 2023-11-09 22:17 UTC by CalebRas

## Description

This PR implements `Find closest facility from point` in `Routing and Logistics` category.
URL to README: [README](https://github.com/Esri/arcgis-maps-sdk-swift-samples/tree/Caleb/New-FindClosestFacilityFromPoint/Shared/Samples/Find%20closest%20facility%20from%20point)

## Linked Issue(s)

- `swift/issues/4648`

## How To Test

- Tap "Solve Routes" to solve and display the route from each incident to the closest facility.
- Tap "Reset" to reset the routes.

## Screenshots

![find-closest-facility-from-point](https://github.com/Esri/arcgis-maps-sdk-swift-samples/assets/34120440/ca6b331e-47fb-4bf6-9aac-a2c27e11023a)

2023-11-09 22:33 UTC, CalebRas commented
Removed @mhdostal since he is already a reviewer on a current samples PR.

2023-11-13 19:59 UTC, des12437 commented on Shared/Samples/Find closest facility from point/FindClosestFacilityFromPointView.swift
> +    @State private var routing = false
```suggestion
    @State private var isRouting = false
```
This Boolean does not read as an assertion. Feel free to use a different name than suggested.

2023-11-13 21:03 UTC, des12437 submitted a review, later dismissed

2023-11-14 16:12 UTC, njarecha requested changes
Looks good, just a comment and a suggestion.

2023-11-14 16:12 UTC, njarecha commented on Shared/Samples/Find closest facility from point/FindClosestFacilityFromPointView.swift
> +            }
Good to move closestFacilityRoute as part of guard as no point in creating the `Graphic` if route geometry is not available.
```suggestion
            let routeGraphics = incidentsIndices.compactMap { incidentIndex -> Graphic? in
                // Get the index for the facility closest to the given incident and facility route.
                guard let closestFacilityIndex = closestFacilityResult.rankedIndexesOfFacilities(
                    forIncidentAtIndex: incidentIndex
                ).first,
                      let closestFacilityRoute = closestFacilityResult.route(
                        toFacilityAtIndex: closestFacilityIndex,
                        fromIncidentAtIndex: incidentIndex
                      ) else {
                    return nil
                }
                
                // Create a graphic using the route's geometry.
                return Graphic(geometry: closestFacilityRoute.routeGeometry, symbol: routeSymbol)
            }
```

2023-11-15 00:39 UTC, CalebRas commented on Shared/Samples/Find closest facility from point/FindClosestFacilityFromPointView.swift
> +    @State private var errorAlertIsShowing = false
Based on the discussion in `swift/issues/4648`, it looks this is going to get removed in Sprint X, so I think it is good to leave as is for now.

2023-11-15 00:41 UTC, njarecha approved these changes

2023-11-15 00:44 UTC, des12437 approved these changes

2023-11-15 17:14 UTC, merged