[Update] Clustering sample names
Esri/arcgis-maps-sdk-swift-samples pull request #348
Opened 2024-03-01 21:24 UTC by CalebRas

## Description

This PR updates the `Add clustering feature reduction to a point feature layer` and `Display points using clustering feature reduction` sample names to match their updated common designs.
URL to READMEs: [Configure clusters](https://github.com/Esri/arcgis-maps-sdk-swift-samples/tree/Caleb/Update-ClusteringSampleNames/Shared/Samples/Configure%20clusters), [Display clusters](https://github.com/Esri/arcgis-maps-sdk-swift-samples/tree/Caleb/Update-ClusteringSampleNames/Shared/Samples/Display%20clusters)

`Add clustering feature reduction to a point feature layer` -> `Configure clusters`

`Display points using clustering feature reduction` -> `Display clusters`

## Linked Issue(s)

- `swift/issues/4989`

## How To Test

- Ensure all the name changes are correct.
- Ensure the samples load and preform as expected.

## Screenshots

|Before|After|
|:-:|:-:|
|    ![add-clustering-feature-reduction-to-a-point-feature-layer](https://github.com/Esri/arcgis-maps-sdk-swift-samples/assets/34120440/292e4809-2391-40b3-9795-35a283857cc8)    |    ![configure-clusters](https://github.com/Esri/arcgis-maps-sdk-swift-samples/assets/34120440/7249f57f-de82-4043-8f8c-44a1a5a0a78c)    |
|    ![display-points-using-clustering-feature-reduction](https://github.com/Esri/arcgis-maps-sdk-swift-samples/assets/34120440/8a531703-ff48-41dc-a585-e9fb42edb3ad)    |    ![display-clusters](https://github.com/Esri/arcgis-maps-sdk-swift-samples/assets/34120440/6d6cf06e-5083-4706-89c4-351754eeb3d0)    |

2024-03-01 22:58 UTC, njarecha requested changes
Please code files to `Copy Source Code Files` to prevent the crash.

2024-03-01 23:00 UTC, yo1995 requested changes
Please also update the "Copy Source Code Files" phase.

2024-03-01 23:11 UTC, njarecha approved these changes

2024-03-01 23:20 UTC, yo1995 approved these changes

2024-03-01 23:30 UTC, merged

2024-03-19 20:53 UTC, yo1995 commented
We'll need to use the `redirect_from` field in metadata as the samples were public in the previous release before we make this rename.